# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rails-gui 0.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "rails-gui".freeze
  s.version = "0.0.4".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Andy Maleh".freeze]
  s.date = "2025-04-11"
  s.description = "Rails Graphical User Interface - User-Friendly Rails Configuration (e.g. display routes in a table, run rails commands visually, etc...)".freeze
  s.email = "andy.am@gmail.com".freeze
  s.executables = ["rails-gui".freeze]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "VERSION",
    "app/rails-gui.rb",
    "app/rails_gui/model/rails_command.rb",
    "app/rails_gui/view/main_window.rb",
    "bin/rails-gui",
    "rails-gui.gemspec"
  ]
  s.homepage = "http://github.com/AndyObtiva/rails-gui".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.6.7".freeze
  s.summary = "Rails Graphical User Interface".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<glimmer-dsl-libui>.freeze, ["~> 0.12.8".freeze])
  s.add_development_dependency(%q<shoulda>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12".freeze])
  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.4.9".freeze])
  s.add_development_dependency(%q<simplecov>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<puts_debuggerer>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<rake-tui>.freeze, [">= 0".freeze])
end
